channels:
  - conda-forge
dependencies:
  # Absolutely necessary
  - python=3.12
  - numpy=2.1 # For processing arrays
  - pandas=2.2 # Processing "data frames" (tables)
  - matplotlib # For plots

  # Notebook
  - jupyterlab
  - ipykernel
  - nbconvert # Convert notebook to html
  - jupytext # Sync notebook <-> plaintext

  # Other dependencies
  - seaborn # More plots, delegates to matplotlib
  - black # Formatting your code
  - einops # Operate on arrays with Einstein notation
  - scipy # Various scientific computing things
  - pip # Python package manager
  - pip: [] # Dependencies to be installed through pip go here
